<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Post;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
//         Post::create([
//             'user_id' => '1',
//             'nama_apk'=> 'Sistem Informasi Capaian dan Monitoring Pengadaan Secara Elektronik (SICAMPERENIK)',
//             'versi' => '-',
//             'nomor_sk' => '188.45/207-PBJ/2020',
//             'tahun_sk' => '2020',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Ujang Miftahudin, SE',
//             'nomor_wa' => '085659512002',
//             'email' => 'u.miftahudin08@gmail.com',
//             'jumlah_pengguna' => '31',
//             'alamat_web' => 'https://bpbj.sukabumikota.go.id/',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Sistem Informasi Capaian dan Monitoring Pengadaan Secara Elektronik (SICAMPERENIK)
//             sebagai aplikasi yang mendukung penyelenggaraan Pengadaan barang/Jasa Pemerintah
//             yang di kelola oleh Bagian Pengadaan Barang/Jasa Sekretariat Daerah Kota Sukabumi,
            
//             mempunyai fungsi pokok sebagai media informasi dan pengelolaan capaian serta
//             monitoring penyelenggaraan proses layanan pengadaan secara elektronik di Kota
//             Sukabumi, Aplikasi Sicamperenik terintegrasi dengan penyelenggaraan sistem informasi
//             Pemerintah Kota Sukabumi dan sistem pengelolaan pengadaan barang/jasa pemerintah
//             secara elektronik sesuai peraturan perundang-undangan yang berlaku.
//             Manfaat dari adanya Aplikasi ini antara lain ; memudahkan para pelaku pengadaan
//             barang/jasa dari proses pengajuan, penyerahan berkas, disposisi, sampai dengan
//             persiapan kaji ulang RPP. Menyajikan Laporan Capaian dan media monitoring
//             Penyelenggaraan Pengadaan barang/jasa di lingkungan Pemerintah Kota Sukabumi, baik
//             yang dilaksanakan dengan metode Tender maupun non tender.',
//             'sop' => '-',
//             'pemilik' => 'Kota',
//             'tampilan' => '-',
//             'pelatihan' => 'Belum ada',
//             'rapat' => '-',
//             'bug' => 'Ya ada',
//             'kendala' => 'Tidak ada',
//         ]);

//         Post::create([
//             'user_id' => '1',
//             'nama_apk'=> 'E-Form Permbukaan Rekening PERUMDA BPR KOTA SUKABUMI',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Novi Nivelia',
//             'nomor_wa' => '0895332329997',
//             'email' => 'pelayanan@bprkotasukabumi.co.id',
//             'jumlah_pengguna' => '2',
//             'alamat_web' => 'https://bprkotasukabumikota.go.id/index.html',
//             'jenis_layanan' => 'Untuk Masyarakat Umum (G2C)',
//             'uraian' => 'Layanan Pembukaan Rekening data awal untuk selanjutnya di tindak lanjuti oleh petugas lapangan.',
//             'sop' => '-',
//             'pemilik' => 'Pusat',
//             'tampilan' => '-',
//             'pelatihan' => 'Tidak ada',
//             'rapat' => '-',
//             'bug' => 'Ya ada',
//             'kendala' => 'Email Notifikasi Pembuaan Tabungan Kadang sampai terlambat',
//         ]);

//         Post::create([
//             'user_id' => '1',
//             'nama_apk'=> 'E-ANJAB-ABK KEMENDAGRI',
//             'versi' => '1.0',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Diny Sukmaningsih',
//             'nomor_wa' => '08154638186',
//             'email' => 'organisasi@sukabumikota.co.id',
//             'jumlah_pengguna' => '31',
//             'alamat_web' => 'https://bprkotasukabumikota.go.id/index.html',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Aplikasi yang dikelola oleh Biro Organisasi dan Tata Laksana Kemendagri untuk input data ANJAB ABK bagi seluruh Pemerinah Daerah baik Provinsi maupun Kabupaten/Kota.',
//             'sop' => '-',
//             'pemilik' => 'Pusat',
//             'tampilan' => '-',
//             'pelatihan' => 'Ada, dalam bentuk kegiatan Bimtek Input Data ANJAB ABK menggunakan aplikasi E-ANJAB-ABK Kemendagri, tanggal 18 November 2022, dengan jumlah peserta sebanyak 62 orang',
//             'rapat' => '-',
//             'bug' => 'Ada, Brio organisasi dan Tata Laksana Setjen Kemendagri',
//             'kendala' => 'Ada, terutama apabila aplikasi dalam masa pemelihaaan (maintenance) dan apabila koneksi internet tidak stabil atau lemah', 
//         ]);

//         Post::create([
//             'user_id' => '1',
//             'nama_apk'=> 'SIMONA UNTUK TPP (SISTEM INFORMASI MONITORING DAN EVALUASI BIDANG ANALISA JABATAN)',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Diny Sukmaningsih',
//             'nomor_wa' => '08154638186',
//             'email' => 'organisasi@sukabumikota.co.id',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'https://bprkotasukabumikota.go.id/index.html',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Aplikasi yang dikelola oleh Biro Organisasi dan Tata Laksana Kemendagri untuk input data ANJAB ABK bagi seluruh Pemerinah Daerah baik Provinsi maupun Kabupaten/Kota.',
//             'sop' => '-',
//             'pemilik' => 'Pusat',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Ada, Brio organisasi dan Tata Laksana Setjen Kemendagri',
//             'kendala' => 'Ada, terutama apabila aplikasi dalam masa pemelihaaan (maintenance) dan apabila koneksi internet tidak stabil atau lemah', 
//         ]);

        
//         Post::create([
//             'user_id' => '1',
//             'nama_apk'=> 'E-APARATUR PEMERINTAH KOTA SUKABUMI',
//             'versi' => '2.0',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Tidak Aktif',
//             'alasan' => 'Kendala tidak adanya SDM TIK dengan kendala anggaran',
//             'nama_admin' => 'Diny Sukmaningsih',
//             'nomor_wa' => '08154638186',
//             'email' => 'organisasi@sukabumikota.co.id',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'https://e-aparatur.sukabumikota.co.id',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Aplikasi yang dikelola oleh bagian Organisasi Setda Kota Sukabumi untuk input dana Analisa Jabatan dan Analisa Beban Kerja (ANJAB ABK) serta Evaluasi Jabatan (EVJAB) bagi seluruh perangkat daerah di lingkungan Pemerintah Daerah Kota Sukabumi.',
//             'sop' => '-',
//             'pemilik' => 'Kota',
//             'tampilan' => '-',
//             'pelatihan' => 'Dalam bentuk Bimtek Penyusunan ANJAB, ABK dan EVJAB secara hybrid, pada tanggal 25 Februari 2021, dengan jumlah peserta 112 orang.',
//             'rapat' => '-',
//             'bug' => 'Ada, INJABAR UNPAD',
//             'kendala' => 'Ada, terutama apabila aplikasi dalam masa pemelihaaan (maintenance) dan apabila koneksi internet tidak stabil atau lemah', 
//         ]);
        
//         Post::create([
//             'user_id' => '1',
//             'nama_apk'=> 'SINOVIK',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Fery Munggaram, S.STP, M.A.P',
//             'nomor_wa' => '085725121617',
//             'email' => 'orgkotasmi@gmail.com',
//             'jumlah_pengguna' => '16',
//             'alamat_web' => 'https://sinovik.menpan.go.id',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Aplikasi web untuk penginputan kompetisi inovasi pelayanan publik yang diselenggarakan kemenpanrb',
//             'sop' => '-',
//             'pemilik' => 'Pusat',
//             'tampilan' => '-',
//             'pelatihan' => 'Ada melalui youtube dengan alamat  https://www.youtube.com/@sinovikkementarianpanrb4983',
//             'rapat' => '-',
//             'bug' => 'Ada, ibu rizki dari kemenpanRB',
//             'kendala' => 'Terkadang untuk admin upp susah masuk (login)', 
//         ]);

//         Post::create([
//             'user_id' => '1',
//             'nama_apk'=> 'SIPPN (system informasi penyelenggaraan pelayanan publik nasional)',
//             'versi' => '-',
//             'nomor_sk' => 'Kepunyaan KemenpanRB',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Fery Munggaram, S.STP, M.A.P',
//             'nomor_wa' => '085725121617',
//             'email' => 'orgkotasmi@gmail.com',
//             'jumlah_pengguna' => '-',
//             'alamat_web' => 'https://sippn.menpan.go.id',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Sistem informasi penyelenggaraan pelayanan publik nasional yang dibuat oleh kemenpanRB guna menghimpun data pelanyanan public secara Nasional',
//             'sop' => '-',
//             'pemilik' => 'Pusat',
//             'tampilan' => '-',
//             'pelatihan' => 'Ada melalui youtube dengan alamat  https://www.youtube.com/watch?v=KFq4laflPvY',
//             'rapat' => '-',
//             'bug' => 'Helpdesk kemenpanRB',
//             'kendala' => 'tidak ada', 
//         ]);

//         Post::create([
//             'user_id' => '1',
//             'nama_apk'=> 'Hai Garlik (halaman Informasi Penyelenggaraan pelayanan Publik)',
//             'versi' => '1.0',
//             'nomor_sk' => 'Pedoman belum di kepWalkan baru berupa petunjuk pelakasanaan',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Nurkania Sari Dewi, S.T',
//             'nomor_wa' => '089629767240',
//             'email' => 'orgkotasmi@gmail.com',
//             'jumlah_pengguna' => '49',
//             'alamat_web' => 'https://bagianorganisasi.sukabumikota.go.idhai-garlik',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Halaman informassi penyelenggaraan pelayanan publik (HAI GARLIK) adalah aplikasi web untuk melakukan selft assesment pemantauan dan evaluasi penyelenggaraan pelanyanan publik (PEKPPP) sesuai dengan peraturan perundang-undangan',
//             'sop' => '-',
//             'pemilik' => 'Kota',
//             'tampilan' => '-',
//             'pelatihan' => 'Ya, ada dengan peserta terdisi dari 49 operator UPP dan 4 evaluator (bagian organisasi)',
//             'rapat' => '-',
//             'bug' => 'Aplikasi dibuat sendiri tanpa pihak ketiga',
//             'kendala' => 'tidak ada', 
//         ]);

//         Post::create([
//             'user_id' => '1',
//             'nama_apk'=> 'E-Performance',
//             'versi' => '2.0',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Tidak Aktif',
//             'alasan' => 'Aplikasi tidak terpakai',
//             'nama_admin' => 'Asep Rahmat, S.kep., M.AP',
//             'nomor_wa' => '081320149339',
//             'email' => 'organisasi@sukabumikota.go.id',
//             'jumlah_pengguna' => '15',
//             'alamat_web' => 'https://eperformence.sukabumi.go.id',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Sistem akuntabilitas kinerja instansi pemerintah. Pemerintah Kota Sukabumi',
//             'sop' => '-',
//             'pemilik' => 'Kota',
//             'tampilan' => '-',
//             'pelatihan' => 'Tidak Ada',
//             'rapat' => '-',
//             'bug' => 'Ada, bagian organisasi Setda Kota Sukabumi',
//             'kendala' => 'tidak ada', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'Poin Organisasi',
//             'versi' => '2.0',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Tidak Aktif',
//             'alasan' => 'Server tidak bisa di akses oleh admin dan semua client.',
//             'nama_admin' => 'Asep Rahmat, S.kep., M.AP',
//             'nomor_wa' => '081320149339',
//             'email' => 'organisasi@sukabumikota.go.id',
//             'jumlah_pengguna' => '15',
//             'alamat_web' => 'https://poinorganisasi.sukabumi.go.id',
//             'jenis_layanan' => 'Untuk Masyarakat Umum (G2C)',
//             'uraian' => 'Poin Organisasi atau Pojok Informasi Bagian Organisasi adalah Aplikasi untuk mempublikasikan informasi seputar kegiatan yang dilaksanakan dan penyimpanan data cadangan untuk bagian Organisasi Setda Kota Sukabumi.',
//             'sop' => '-',
//             'pemilik' => 'Kota',
//             'tampilan' => '-',
//             'pelatihan' => 'Tidak Ada',
//             'rapat' => '-',
//             'bug' => 'Ada, bagian organisasi Setda Kota Sukabumi',
//             'kendala' => 'Ada, saat ini 30 Mei 2023 web dan server tidak bisa diakses oleh semua pengguna.', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'E-SAKIP Reviu',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Asep Rahmat, S.kep., M.AP',
//             'nomor_wa' => '081320149339',
//             'email' => 'organisasi@sukabumikota.go.id',
//             'jumlah_pengguna' => '31',
//             'alamat_web' => 'https://esr.mempan.go.id',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'E-SAKIP Reviu adalah sistem aplikasi yang dibangun oleh Kementerian Pendanyagunaan Aparatur Negara dan Reformasi Birokrasi sebagai upaya peningkatan kualitas pelaksanaan akuntabilitas kinerja di lingkungan instansi pemerintah untuk mengingkatkan efektivitas dan efisiensi penggunaan anggaran.',
//             'sop' => '-',
//             'pemilik' => 'Pusat',
//             'tampilan' => '-',
//             'pelatihan' => 'Tidak Ada',
//             'rapat' => '-',
//             'bug' => 'Ada, Kementerian Pendanyagunaan Aparatur Negara dan Reformasi Birokrasi',
//             'kendala' => 'Tidak Ada', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'Pelayanan Tekonologi Informasi Keluar Masuk Surat (Peti kemas)',
//             'versi' => '2.0',
//             'nomor_sk' => '01',
//             'tahun_sk' => '2020',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Nining Pancawati, S.Kom',
//             'nomor_wa' => '08161991854',
//             'email' => 'pancawatinining@gmail.com',
//             'jumlah_pengguna' => '6',
//             'alamat_web' => 'https://petikemas.citamiangsukabumikota.com/',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Hadirnya PETI KEMAS mampu mewujudkan sebuah tata kelola administrasi perkantoran yang handal, terutama kecepatan dalam pengambilan keputusan terhadap surat yang masuk. Dimana sebelumnya pengambilan keputusan melalui pendisposisian surat masuk dihadapkan dengan lamanya waktu hingga 2 (dua) hari (karena intensitas kegiatan Camat dan Lurah sangat tinggi). Namun setelah hadirnya aplikasi PETI KEMAS ini, pendisposisian surat masuk hanya membutuhkan waktu paling lama 30 (Tiga Puluh) Menit saja untuk dapat langsung didistribusikan dari pimpinan kepada bawahan. Sehingga dari sisi kuantitas, surat masuk yang didisposisi pimpinan pada hari itu juga mencapai 100%, dibandingkan sebelum adanya inovasi yang hanya mencapai sekitar 40%.',
//             'sop' => '-',
//             'pemilik' => '-',
//             'tampilan' => '-',
//             'pelatihan' => 'Ada, pada tahun 2020',
//             'rapat' => '-',
//             'bug' => 'Ada,',
//             'kendala' => 'Tidak Ada', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'SI BEO (Sistem Informasi Berbasis Elektronik',
//             'versi' => '1.0',
//             'nomor_sk' => '800/404/CBR/2020',
//             'tahun_sk' => '2020',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Ahmad Hoppy Purnama',
//             'nomor_wa' => '085216061520',
//             'email' => 'ahmadhoppy@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'https://kecamatancibeureum.com',
//             'jenis_layanan' => 'Untuk Masyarakat Umum (G2C)',
//             'Uraian' => 'SIBEO merupakan sistem informasi layanan administrasi dan keluhan masyarakat terhadap layanan administrasi dan meneruskan / memfasilitasi keluhan masyarakat terhadap layanan SKPD/instusi lain',
//             'sop' => '-',
//             'pemilik' => 'Kota',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Ada',
//             'kendala' => 'Fitur yang terdapat di aplikasi belum optimal khususnya untuk pelayanan terhadap warga. Sehingga perlu adanya pembaruan yang saat ini sedang di diskusikan dengan pihak penyedia website.', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'OSS RBA',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Drs. Didin Syarifudin, M.Si.',
//             'nomor_wa' => '085721039588',
//             'email' => 'didinsf13@gmail.com',
//             'jumlah_pengguna' => '8',
//             'alamat_web' => 'https://oss.go.id/',
//             'jenis_layanan' => 'Untuk Masyarakat Umum (G2C)',
//             'Uraian' => 'Online Single Submission Risk Based Approach (OSS-RBA) atau Perizinan Berusaha
//             Berbasis Risiko adalah perizinan berusaha yang diberikan kepada pelaku usaha untuk memulai dan menjalankan kegiatan usahanya yang dinilai berdasarkan tingkat risiko kegiatan usaha.
//             Manfaat : memfasilitasi pelaku usaha agar terhubung dengan semua stakeholder dan memperoleh izin secara aman, cepat dan real time se ta untuk memfasilitasi pelaku usaha dalam melakukan pelaporan dan pemecahan masalah perizinan dalam satu tempat.',
//             'sop' => '-',
//             'pemilik' => 'Pusat',
//             'tampilan' => '-',
//             'pelatihan' => 'Ya tingkat nasional. Sejak tahun 2020 sampai 2022, dengan jumlah peserta yang sudah mengikuti pelatihan 9 orang.',
//             'rapat' => '-',
//             'bug' => 'Ada. Tim OSS dari Kementrian Investasi / BKPM',
//             'kendala' => 'Ada, Belum semua proses perizinan dan non perizinan masuk dalam aplikasi OSS REA', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'PENDAKI',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Tidak Aktif',
//             'alasan' => 'Karena Disporapar Kota Sukabumi Untuk Tahun ini Tidak memperoleh DAK Non Fisik.',
//             'nama_admin' => 'Yosi Rifil Kotel, S.E',
//             'nomor_wa' => '0812 2244 1877',
//             'email' => 'yrkotel@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'https://pendaki.go.id/',
//             'jenis_layanan' => 'Untuk Pemerintahan(G2G)',
//             'Uraian' => 'Input data hasil pelatihan, nama peserta pelatihan dan nama narasumber.',
//             'sop' => '-',
//             'pemilik' => 'Pusat',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Kemenparekraf',
//             'kendala' => 'Ada, Sering terjadinya eror karena akses yang penuh.', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'parbuddalamangka',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Wita Puri Garyati',
//             'nomor_wa' => '085724815550',
//             'email' => 'zeefvannazee@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'parbuddalamangka.co.id',
//             'jenis_layanan' => 'Untuk Pelaku Usaha(G2B)',
//             'Uraian' => 'Pendataan Jumlah Destinasi Pariwisata di Kota Sukabumi',
//             'sop' => '-',
//             'pemilik' => 'Provinsi',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Dinas Pariwisata dan Budaya Provinsi Jawa Barat',
//             'kendala' => 'Ada, Aplikasi eror saat penginputan.', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'parbuddalamangka',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Wita Puri Garyati',
//             'nomor_wa' => '085724815550',
//             'email' => 'zeefvannazee@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'parbuddalamangka.co.id',
//             'jenis_layanan' => 'Untuk Pelaku Usaha(G2B)',
//             'Uraian' => 'Pendataan Jumlah Destinasi Pariwisata di Kota Sukabumi',
//             'sop' => '-',
//             'pemilik' => 'Provinsi',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Dinas Pariwisata dan Budaya Provinsi Jawa Barat',
//             'kendala' => 'Ada, Aplikasi eror saat penginputan.', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'Simaungjabarprov.go.id',
//             'versi' => '-',
//             'nomor_sk' => 'KP.06.01/061/Disporapar',
//             'tahun_sk' => '2023',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Fitri Rhamdianti N',
//             'nomor_wa' => '085723009019',
//             'email' => 'bidangolahraga990@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'pendaki.go.id',
//             'jenis_layanan' => 'Untuk Masyarakat Umum (G2C)',
//             'Uraian' => 'Untuk pendaftaran atlit se-Jawa Barat',
//             'sop' => '-',
//             'pemilik' => 'Provinsi',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Dispora Provinsi Jawa Barat',
//             'kendala' => 'Ada, Server.', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'SIAP KERJA',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Mellani Fitra Rizkianty, S.P, M.Si',
//             'nomor_wa' => '081578944814',
//             'email' => 'melanifitrarizkianty@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'karirhub.kemnaker.go.id',
//             'jenis_layanan' => 'Untuk Masyarakat Umum (G2C)',
//             'Uraian' => 'Aplikasi SIAP KERJA digunakan untuk membuat kartu Kuning/AK1 yang digunakan para pencari kerja untuk salah satu persyaratan melamar pekerjaan, dan Aplikasi SIAP KERJA juga turut menyediakan lowongan pekerjaan dar perusahaan yang ada di seluluh Indonesia, untuk memudahkan para pencari kerja melamar pekerjaan.
//             ',
//             'sop' => '-',
//             'pemilik' => 'Pusat',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => '-',
//             'kendala' => 'Kadang terjadi error dari pusat', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'SISKOTKIN (Sistem Komputerisasi Tenaga Kerja Luar Negri)',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Mellani Fitra Rizkianty, S.P, M.Si',
//             'nomor_wa' => '081578944814',
//             'email' => 'melanifitrarizkianty@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'siskotkin.bnp2tki.go.id',
//             'jenis_layanan' => 'Untuk Masyarakat Umum (G2C)',
//             'Uraian' => 'Aplikasi ini digunakan untuk rekomendasi dari Disnaker untuk ke Pihak imigrasi guna memenuhi persyaratan untuk bekerja ke luar Negeri',
//             'sop' => '-',
//             'pemilik' => 'Pusat',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => '-',
//             'kendala' => 'Kadang terjadi gangguan dari pusat', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'Online Data System (ODS) Koperasi',
//             'versi' => '1.0',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Syaiful Akbar, SM',
//             'nomor_wa' => '085846924078',
//             'email' => 'diskumindagsukabumi@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'http://www.kemenkopukm.go.id',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'Uraian' => 'Sebuah sistem untuk pendataan koperasi agar data koperasi lebih akurat. Manfaatnya adalah Updating data koperasi',
//             'sop' => '-',
//             'pemilik' => 'Pusat',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Kementerian Koperasi dan UKM',
//             'kendala' => '-', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'Surat Keterangan Asal-E-ska',
//             'versi' => '1.0',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Rismawan, SE',
//             'nomor_wa' => '081564830843',
//             'email' => 'diskumindagsukabural@gmail.com',
//             'jumlah_pengguna' => '6',
//             'alamat_web' => 'https://e-ska.kemendag.go.id',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'Uraian' => 'Surat Keterangan Asal (SKA) atau biasa disebut Certificate of Origin (COO) adalah merupakan sertifikasi asal barang, dimana dinyatakan dalam sertifikat tersebut bahwa barang/komoditas yang diekspor adalah berasal dari daerah/negara pengekspor. Mendasari hal ini adalah kesepakatan bilateral, regional, multilateral, unilateral atau karena ketentuan sepihak dari suatu negara pengimpor/ tujuan, yang mewajibkan SKA/COO ini disertakan pada barang ekspor Indonesia. COO / SKA ini yang membuktikan bahwa barang tersebut berasal, dihasilkan dan atau diolah di Indonesia',
//             'sop' => '-',
//             'pemilik' => 'Pusat',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Kementerian Perdagangan',
//             'kendala' => '-', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'Sistem Pemantauan Pasar dan Kebutuhan Pokok (SP2KP)',
//             'versi' => '1.0',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Tedi Ruswandi',
//             'nomor_wa' => '085210063092',
//             'email' => 'diskumindagsukabumi@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'sp2kp.kemendag.go.id',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'Uraian' => ' Kemendag bekerjasama dengan Pemerintah Provinsi dan Kabupaten/Kota melakukan pengumpulan serta pelaporan data harga dan stok/pasokan bapokting secara harian melalui Sistem Pemantauan Pasar Kebutuhan Pokok (SP2KP).',
//             'sop' => '-',
//             'pemilik' => 'Pusat',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Kementerian Perdagangan',
//             'kendala' => '-', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'Sistem Informasi Pengendalian Inflasi Daerah (Si Linda)',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Rismawan, SE',
//             'nomor_wa' => '081564830843',
//             'email' => 'diskumindagsukabumi@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'https://silinda.jabarprov.go.id',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)', 
//             'uraian' => 'Setiap Kabupaten/Kota membentuk Tim Pengendali Inflasi Daerah untuk mengevaluasi fluktuasi harga komoditas',
//             'sop' => '-',
//             'pemilik' => 'Provinsi',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Pemerintah Provinsi Jawa Barat',
//             'kendala' => '-', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'Sistem Informasi Industri Nasional (Slinas)',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Enang Dulkipli',
//             'nomor_wa' => '085846839214',
//             'email' => 'diskumindagsukabumi@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'https://siinas.kemenperin.go.id/',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Setiap Kabupaten/Kota membentuk Tim Pengendali Inflasi Daerah untuk mengevaluasi fluktuasi harga komoditas',
//             'sop' => '-',
//             'pemilik' => '-',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Kementerian Perindustrian',
//             'kendala' => '-', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'Sistem Online Single Submission (OSS)',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Hera Haqiqi',
//             'nomor_wa' => '085846839214',
//             'email' => 'diskumindagsukabumi@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'https://oss.go.id/',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Penyelenggaraan Perizinan Berusaha Berbasis Risiko metalul Sistem Online Single Submission (OSS) merupakan pelaksanaan Undang-Undang Nomor 2 Tahun 2022 Tentang Cipta Kerja. OSS Berbasis Risiko wajib digunakan oleh Pelaku Usaha, Kementerian/Lembaga, Pemerintah Daerah, Administrator Kawasan Ekonomi Khusus (KEK) dan Badan Pengusahaan Kawasan Perdagangan Bebas Pelabuhan Bebas (KPBPB). Berdasarkan Peraturan Pemerintah Nomor 5 Tahun 2021 terdapat 1.702 kegiatan usaha yang terdiri atas 1.349 Klasifikasi Baju Lapangan Usaha Indonesia (KBLI) yang sudah diimplementasikan dalam Sistem OSS Berbasis Risiko.',
//             'sop' => '-',
//             'pemilik' => '-',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Kementerian Investasi/BKPM',
//             'kendala' => '-', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'PUSAKA-Pendaftaran Sertifikasi Halal',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Hera Haqiqi',
//             'nomor_wa' => '085846839214',
//             'email' => 'diskumindagsukabumi@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'https://pusaka.kemenag.go.id/login/',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Pusaka merupakan aplikasi yang menghadirkan berbagai fitur layanan online Kementerian Agama untuk masyarakat. Misalnya, pendaftaran haji, pendaftaran nikah, sertifikasi halal, dan lain-lain.',
//             'sop' => '-',
//             'pemilik' => '-',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Kementerian Agama',
//             'kendala' => '-', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'Pendaftaran Merek (Haki)',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Hera Haqiqi',
//             'nomor_wa' => '085846839214',
//             'email' => 'diskumindagsukabumi@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'https://merek drip.go.id/',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Merek adalah tanda yang dapat ditampilkan secara grafis berupa gambar, logo, nama, kata, huruf, angka, susunan warna, dalam bentuk 2 (dua) dimensi dan/atau 3 (tiga) dimensi, suara, hologram, atau kombinasi dari 2 (dua) atau lebih unsur tersebut untuk membedakan barang dan/atau jasa yang diproduksi oleh orang atau badan hukum dalam kegiatan perdagangan barang dan/atau jasa. Apakah fungsi pendaftaran Merek itu?Pendaftaran Merek berfungsi sebagai: Alat bukti bagi pemilik yang berhak atas Merek yang didaftarkan;Dasar penolakan terhadap Merek yang sama keseluruhan atau sama pada pokoknya yang dimohonkan pendaftaran oleh orang lain untuk barang/jasa sejenisnya;Dasar untuk mencegah orang lain memakai Merek yang sama keseluruhan atau sama pada pokoknya dalam peredaran untuk barang/jasa sejenisnya.',
//             'sop' => '-',
//             'pemilik' => '-',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Kementerian Hukum dan Ham',
//             'kendala' => '-', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'WEB Dinas Perhubungan Kota ',
//             'versi' => '2020',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'H. Mubarak Ahmad ',
//             'nomor_wa' => '089626629699',
//             'email' => 'hrmagad@gmail.com ',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => ' http://dishub.sukabumikota.go.id/',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Sebagai Media Komunikasi dan Informasi secara Digital untuk Umum maupun Internal serta Eksternal Dari Dinas Perhubungan Kota Sukabumi Kepada Masyarakat umum tentang Kinerja, Layanan yang tersedia pada Dinas, Pengumuman tenntang kondisi dan kejadian aktualisasi di Jalan Raya yang seharusnya terintegrasi dengan ITS/ATCS/CCTV serta produk media komunikasi (Media Sosial) lainnya, Serta sebagai Web portal dalam pelayanan produk yang dimiliki Dinas, seperti andalalin, Load Factor Terminal, CCTV, Hasil Uji kir PKB, serta lainnya.',
//             'sop' => '-',
//             'pemilik' => '-',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'ADMIN WEB',
//             'kendala' => '(halaman awal, proses yang terjadi, contoh keluaran)', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'X-Protect Milstone',
//             'versi' => '2019',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Tidak Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Masagus Idham Wahyudi',
//             'nomor_wa' => '089602489135',
//             'email' => 'hrmagad@gmail.com ',
//             'jumlah_pengguna' => '2',
//             'alamat_web' => '36.66.130.9:8081/index.html',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Pemantauan kondisi arus lalu lintas secara langsung ataupun siaran ulang, dapat juga digunakan untuk Analisa kondisi lalu lintas atau Penyelidikan suatu kejadian seperti Kecelakaan lalu lintas dll',
//             'sop' => '-',
//             'pemilik' => 'Kota',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Tidak (Garansi Habis)',
//             'kendala' => 'Tidak jelaskan jika ada ? Kekurangan dari aplikasi ini belum ada traffic data analytics system. Sehingga untuk penghitungan atau Analisa lalu lintas masih dilakukan secara manual.
//             ', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'PANON PENDEKAR',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Bambang Budhiman, S.Kom',
//             'nomor_wa' => '082213735834',
//             'email' => 'uptpkb@gmail.com',
//             'jumlah_pengguna' => '-',
//             'alamat_web' => ' Ip Server Lokal',
//             'jenis_layanan' => 'Untuk Masyarakat Umum (G2C)',
//             'uraian' => 'PANON PENDEKAR Pembayaran non tunai pengujian kendaraan bermotor 
//             MANFAATNYA       :  Memudahkan masyarakat untuk melakukan transaksi  pembayaran retribusi pengujian/kir secara non  tunai dengan metode e-comerse',
//             'sop' => '-',
//             'pemilik' => 'Kota',
//             'tampilan' => '-',
//             'pelatihan' => 'pelatihan hanya dilakukan  admin aplikasi saja, pada Bulan Maret Tahun 2021, Jumlah 6 Peserta ',
//             'rapat' => '-',
//             'bug' => 'Jika  error pada system kita selau konsultasikan pada penyadia jasa aplikasinya tersebut.',
//             'kendala' => 'Nilai nominal yg harus dibayarkan oleh konsumen tidak tercantum secara automatis.
//             Apabila konsumen akan melakukan pembayaran nilai nominal yg harus dibayarkan harus di input secara manual', 
//         ]);


//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'dinsos.sukabumikota',
//             'versi' => '-',
//             'nomor_sk' => '13',
//             'tahun_sk' => '2020',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Ramlan Yusup',
//             'nomor_wa' => '085794626171',
//             'email' => 'yusupramlan23@gmail.com',
//             'jumlah_pengguna' => '-',
//             'alamat_web' => 'https://dinsos.sukabumikota.go.id/',
//             'jenis_layanan' => 'Untuk Masyarakat Umum (G2C)',
//             'uraian' => 'Website Dinas Sosial
//             Kota Sukabumi adalah platform online yang disediakan oleh Dinas
//             Sosial Kota Sukabumi, Jawa Barat, Indonesia, untuk memberikan
//             informasi dan layanan terkait bidang sosial kepada masyarakat. Situs
//             web ini bertujuan untuk mempermudah aksesibilitas dan komunikasi
//             antara Dinas Sosial dengan masyarakat.',
//             'sop' => '-',
//             'pemilik' => 'Kota',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Tim Pengembang Website: Jika error atau bug terkait dengan
//             fungsi atau tampilan website, Anda dapat menghubungi tim
//             pengembang yang bertanggung jawab atas pembuatan dan pemeliharaan
//             website tersebut. Informasi kontak tim pengembang biasanya dapat
//             ditemukan di bagian kontak atau footer website.',
//             'kendala' => 'Masalah Keamanan: Keamanan aplikasi dapat menjadi perhatian
//             penting. Jika aplikasi tidak memiliki perlindungan yang memadai atau
//             rentan terhadap serangan, ini dapat mengakibatkan kebocoran data
//             atau akses yang tidak sah.', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'Udunan Onlien',
//             'versi' => '-',
//             'nomor_sk' => '16',
//             'tahun_sk' => '2022',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Uus Sandiana',
//             'nomor_wa' => '08567558151',
//             'email' => 'uussandiana2015@gmail.com',
//             'jumlah_pengguna' => '-',
//             'alamat_web' => 'https://www.udunanonline.com/',
//             'jenis_layanan' => 'Untuk Masyarakat Umum (G2C)',
//             'uraian' => 'Salah satu upaya pemerintah Kota Sukabumi untuk mewujudkan
//             kesetiakawanan social ini adalah dengan meluncurkan program Udunan
//             Online yang diharapkan dapat menjadi ‘Wadah untuk penggalangan dana dari masyarakat (tanpa batas) untuk sama-sama membantu saudara-
//             saudara kita yang membutuhkan bantuan. Baik itu bantuan social, kesehatan, perlindungan dan pendampingan.',
//             'sop' => '-',
//             'pemilik' => 'Kota',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Tim Pengembang Website: Jika terjadi error atau bug pada
//             website, Anda dapat menghubungi tim pengembang yang bertanggung
//             jawab atas pembuatan dan pemeliharaan website tersebut. Informasi
//             kontak tim pengembang biasanya dapat ditemukan di halaman "Kontak"
//             atau "Tentang Kami" di website.',
//             'kendala' => 'Masalah Keamanan: Keamanan aplikasi dapat menjadi perhatian
//             penting. Jika aplikasi tidak memiliki perlindungan yang memadai atau
//             rentan terhadap serangan, ini dapat mengakibatkan kebocoran data
//             atau akses yang tidak sah.', 
//         ]);

//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'Siks-NG',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'H. Arif Nur Racman',
//             'nomor_wa' => '081563110688',
//             'email' => '-',
//             'jumlah_pengguna' => '33',
//             'alamat_web' => 'https://siks.kemensos.go.id/',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Siks-NG (Sistem Informasi Kesejahteraan Sosial - Next Generation)
//             adalah sebuah aplikasi yang dikembangkan oleh Kementerian Sosial
//             (Kemensos) Indonesia. Aplikasi ini bertujuan untuk membantu dalam
//             pengelolaan data dan proses administrasi terkait program-program
//             kesejahteraan sosial yang dilaksanakan oleh Kemensos.',
//             'sop' => '-',
//             'pemilik' => 'Pusat',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Tim Dukungan Teknis Kemensos: Kemensos memiliki tim
//             dukungan teknis yang dapat dihubungi jika terjadi masalah teknis pada
//             aplikasi Siks-NG. Anda dapat mencari informasi kontak tim dukungan
//             teknis ini melalui situs web resmi Kemensos atau melalui unit atau bagian
//             yang bertanggung jawab atas pengembangan dan pemeliharaan aplikasi
//             tersebut. Helpdesk Kemensos: Kemensos mungkin memiliki helpdesk atau
//             pusat bantuan yang dapat dihubungi jika Anda mengalami masalah
//             dalam menggunakan aplikasi Siks-NG. Anda dapat mencari informasi
//             kontak helpdesk ini melalui situs web Kemensos atau melalui unit atau
//             bagian terkait.',
//             'kendala' => 'Keterbatasan Fitur: Terkadang, pengguna mungkin menghadapi
//             keterbatasan dalam fitur-fitur yang disediakan oleh aplikasi. Ini dapat
//             menjadi kendala jika pengguna memerlukan fungsi atau kemampuan
//             yang tidak tersedia dalam aplikasi tersebut.', 
//         ]);


//         Post::create([
//             'user_id' => '2',
//             'nama_apk'=> 'Website DPU',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Tidak Aktif',
//             'alasan' => 'Rusak Hardware',
//             'nama_admin' => 'Brigietha',
//             'nomor_wa' => '085721079797',
//             'email' => 'brigiethan@gmail.com',
//             'jumlah_pengguna' => '-',
//             'alamat_web' => 'dpu.sukabumikota.go.id/',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Website dinas PUTR Kota Sukabumi',
//             'sop' => '-',
//             'pemilik' => 'Kota',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => '-',
//             'kendala' => '-.', 
//         ]);

//         Post::create([
//             'user_id' => '3',
//             'nama_apk'=> 'Sistem Informasi Pemerintahan Daerah',
//             'versi' => '2019',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Deni Suryana',
//             'nomor_wa' => '082113378959',
//             'email' => 'suryanadeni72@gmail.com',
//             'jumlah_pengguna' => '25',
//             'alamat_web' => ':https://sukabumi.sipd.kemendagri.go.id/daerah',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'SIPD adalah suatu sistem yang mendokumentasikan, mengadministrasikan, serta mengolah data pembangunan daerah menjadi informasi yang disajikan kepada masyarakat dan sebagai bahan pengambilan keputusan dalam rangka perencanaan, pelaksanaan, evaluasi kinerja pemerintah daerah.',
//             'sop' => '-',
//             'pemilik' => 'Kota',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Ada, BAPPEDA Kota Sukabumi',
//             'kendala' => 'Aplikasi Sering kall lambat dan error', 
//         ]);

//         Post::create([
//             'user_id' => '4',
//             'nama_apk'=> 'E-Lapor',
//             'versi' => '3.4',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Deni Suryana',
//             'nomor_wa' => '082113378959',
//             'email' => 'suryanadeni72@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'https://www.lapor.go.id/',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Sistem Pengelolaan Pengaduan Pelayanan Publik Nasional (SP4N)-Layanan Aspirasi dan Pengaduan Online Rakyat (LAPOR!) adalah layanan penyampaian semua aspirasi dan pengaduan masyarakat Indonesia melalui beberapa kanal pengaduan yaitu website www.lapor.go.id, SMS 1708 (Telkomsel, Indosat, Three). Twitter @lapor1708 serta aplikasi mobile (Android dan iOS). Lembaga pengelola SP4N-LAPOR! adalah Kementerian Pendayagunaan Aparatur Negara dan Reformasi Birokrasi (Kementerian PANRB) sebagai Pembina Pelayanan Publik, Kantor Staf Presiden (KSP) sebagai Pengawas Program Prioritas Nasional dan Ombudsman Republik Indonesia sebagai Pengawas Pelayanan Publik. LAPOR! telah ditetapkan sebagai Sistem Pengelolaan Pengaduan Pelayanan Publik Nasional (SP4N) berdasarkan Peraturan Presiden Nomor 76 Tahun 2013 dan Peraturan Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi Nomor 3 Tahun 2015.',
//             'sop' => '-',
//             'pemilik' => 'Pusat',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => ' Ada, 1. Help desk pada aplikasi 2. Diskominfo',
//             'kendala' => '-', 
//         ]);

//         Post::create([
//             'user_id' => '5',
//             'nama_apk'=> 'Manajemen Vocakasi',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Emis Misbahudin',
//             'nomor_wa' => '085759991921',
//             'email' => 'emismisbahudin78@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'manajenmen.vokasi.kemdikbud.go.id/',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'Seagai aplikasi manajemen yang diberikan oleh direktoral vokasi yang bermanfaat mengetahui jumlah PTK, Kota dan sarpres satuan pendidikan ITKP',
//             'sop' => '-',
//             'pemilik' => '-',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Ada',
//             'kendala' => 'Ada', 
//         ]);

//         Post::create([
//             'user_id' => '6',
//             'nama_apk'=> 'e-SPM',
//             'versi' => '2022',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Deni Suryana',
//             'nomor_wa' => '082113378959',
//             'email' => 'suryanadeni72@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'https://spm.bangda.kemendagri.go.id/',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'e- SPM adalah aplikasi berbasis web yang dirancang untuk menangani proses pengeloaan data terkait capaian SPM yang ada di daerah, sehingga seluruh proses kegiatan dapat terkelola menjadi suatu informasi yang bermanfaat dalam pemanfaatanya.',
//             'sop' => '-',
//             'pemilik' => 'pusat',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Ada, 1. Forum diskusi pada aplikasi',
//             'kendala' => 'Aplikasi Sering kali lambat dan error', 
//         ]);

//         Post::create([
//             'user_id' => '7',
//             'nama_apk'=> 'SUPER',
//             'versi' => '5.0',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Deni Suryana',
//             'nomor_wa' => '082113378959',
//             'email' => 'suryanadeni72@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'https://super.sukabumikota.go.id/',
//             'jenis_layanan' => 'Untuk Masyarakat Umum (G2C)',
//             'uraian' => 'Aplikasi SUPER (Sukabumi Participatory Responder) sebagai sarana masyarakat kota Sukabumi dalam melakukan laporan pengaduan ataupun aspirasi.',
//             'sop' => '-',
//             'pemilik' => 'Kota',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Ada, 1. Diskominfo sebagai pemilik aplikasi',
//             'kendala' => '-', 
//         ]);

//         Post::create([
//             'user_id' => '8',
//             'nama_apk'=> 'E-SAKIP REVIU',
//             'versi' => '2017',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Deni Suryana',
//             'nomor_wa' => '082113378959',
//             'email' => 'suryanadeni72@gmail.com',
//             'jumlah_pengguna' => '1',
//             'alamat_web' => 'https://esr.menpan.go.id/',
//             'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
//             'uraian' => 'e-SAKIP REVIU adalah sistem aplikasi yang dibangun oleh Kementerian Pendayagunaan Aparatur Negara dan Reformasi Birokrasi sebagai upaya peningkatan kualitas pelaksanaan akuntabilitas kinerja di lingkungan instansi pemerintah untuk meningkatkan efektivitas dan efisiensi penggunaan anggaran. Sistem ini bertujuan sebagai sarana pembinaan interaktif pelaksanaan Akuntabilitas kerja instansi pemerintah dan sarana penyampaian laporan kinerja secara online.',
//             'sop' => '-',
//             'pemilik' => 'pusat',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => ' Ada, 1. Help desk pada aplikasi',
//             'kendala' => '-', 
//         ]);

//         Post::create([
//             'user_id' => '9',
//             'nama_apk'=> 'Layanan Konversi Kode Bidang Studi',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Nitia Apsari Rahayuna',
//             'nomor_wa' => '081287196720',
//             'email' => 'lookdaung@gmail.com',
//             'jumlah_pengguna' => '-',
//             'alamat_web' => 'nrg.gtk.kemdikbud.go.id',
//             'jenis_layanan' => 'Untuk Pegawai ANS dan Non ASN (G2E)',
//             'uraian' => 'Cek dan cetak NRG, Konversi kode mata pelanggan, Pengajuan/aktivasi NRG, Pengajuan mutasi antar kementerian',
//             'sop' => '-',
//             'pemilik' => 'pusat',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Admin kemdikbud niskk',
//             'kendala' => '-', 
//         ]);

//         Post::create([
//             'user_id' => '9',
//             'nama_apk'=> 'Layanan Konversi Kode Bidang Studi',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Nitia Apsari Rahayuna',
//             'nomor_wa' => '081287196720',
//             'email' => 'lockdaun90@gmail.com',
//             'jumlah_pengguna' => '-',
//             'alamat_web' => 'nrg.gtk.kemdikbud.go.id',
//             'jenis_layanan' => 'Untuk Pegawai ANS dan Non ASN (G2E)',
//             'uraian' => 'Cek dan cetak NRG, Konversi kode mata pelanggan, Pengajuan/aktivasi NRG, Pengajuan mutasi antar kementerian',
//             'sop' => '-',
//             'pemilik' => 'pusat',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Admin kemdikbud niskk',
//             'kendala' => '-', 
//         ]);

//         Post::create([
//             'user_id' => '10',
//             'nama_apk'=> 'SIM Tunjangan (SIMTUN)',
//             'versi' => '-',
//             'nomor_sk' => '-',
//             'tahun_sk' => '-',
//             'kondisi' => 'Aktif',
//             'alasan' => '-',
//             'nama_admin' => 'Nitia Apsari Rahayuna',
//             'nomor_wa' => '081287196720',
//             'email' => 'lockdaun90@gmail.com',
//             'jumlah_pengguna' => '-',
//             'alamat_web' => 'sintum.gtk.kemdikbud.go.id',
//             'jenis_layanan' => 'Untuk Pegawai ANS dan Non ASN (G2E)',
//             'uraian' => 'Aplikasi Sintum adalah produk yang dikeluarkan oleh kemdikbud tahun 2014 yang digunakan oleh dinas pendidikan kota/kabu untuk mengajan surat keputusan tunjangan protesi (SKTP) bagi guru yang memiliki tunjangan propesi guru (TPG), aplikasi sintum menggunakan data pada lapordik yang telah di validasi untuk memastikan guru tersebut telah memenuhi kriteria penerima tunjangan.',
//             'sop' => '-',
//             'pemilik' => 'pusat',
//             'tampilan' => '-',
//             'pelatihan' => '-',
//             'rapat' => '-',
//             'bug' => 'Admin  niskk',
//             'kendala' => '-', 
//         ]);



//BPBD//
            Post::create([
                'user_id' => '10',
                'nama_apk'=> ' Sistem Informasi elektronik data bencana (Siedan)',
                'versi' => '1.0',
                'nomor_sk' => '-',
                'tahun_sk' => '-',
                'kondisi' => 'Aktif',
                'alasan' => '-',
                'nama_admin' => 'Tasya Maryana',
                'nomor_wa' => '083115513864',
                'email' => 'tasyamaryana1901@gmail.com',
                'jumlah_pengguna' => '1',
                'alamat_web' => 'sukabumikota.go.id/edan/',
                'jenis_layanan' => 'Untuk Pemerintahan (G2G)',
                'uraian' => 'SiEdan merupakan singkatan yang kepanjangannya Sistem Elektronik Data Bencana yang digunakan di Kota Sukabumi berbasis website yang dihubungkan dengan situs www.bpbd.sukabumikota.go.id diterapkan sejak tahun 2020. Berfungsi untuk layanan informasi publik dari berbagai jenis bencana seperti gempa bumi, banjir, longsor, cuaca ektrem, puting beliung dan kebakaran secara real time tentang kebencanaan di Kota Sukabumi serta menjadi Data dan Informasi Bencana yang dimanfaatkan untuk berbagai kepentingan mulai dari analisis dan riset kebencanaan baik perguruan tinggi maupun perusahaan sampai dengan alat pengambil kebijakan di Pemerintah Kota Sukabumi.
                ',
                'sop' => '-',
                'pemilik' => 'Kota',
                'tampilan' => '-',
                'pelatihan' => 'Tahun 2020, Jumlah Peserta 10 Orang',
                'rapat' => '-',
                'bug' => '-',
                'kendala' => '-', 
            ]);


    }
}
